#!/usr/bin/env node
// Regenerates embedded-server.source.ts from embedded-server.mjs.
// The server source ships inside the plugin bundle as a single JSON string
// (opaque to esbuild), so the plugin subprocess can write it deterministically
// to its install location without the plugin knowing its own source path.
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = readFileSync(join(root, "embedded-server.mjs"), "utf8");
const generated = `// Generated by scripts/embed.mjs. Do not edit by hand.
// Inlines embedded-server.mjs as a JSON string so the plugin bundle can carry
// the server without esbuild trying to bundle its imports.
export const EMBEDDED_SERVER_SOURCE: string = ${JSON.stringify(source)};\n`;
writeFileSync(join(root, "embedded-server.source.ts"), generated, "utf8");
console.log(`embedded-server.source.ts written (${source.length} chars)`);